### ISSUE TITLE
"We're unable to complete your request" error

### ISSUE THREAD

**Issue by sudwebd** [jasonjoh/javascript-tutorial#1]
After correctly using the code, 'm getting
```

We're unable to complete your request

Microsoft account is experiencing technical problems. Please try again later.
```
occurs after the login page.
https://login.live.com/err.srf?lc=1033#error=invalid_request&error_description=The+provided+value+for+the+input+parameter+'redirect_uri'+is+not+valid.+The+expected+value+is+'https://login.live.com/oauth20_desktop.srf'+or+a+URL+which+matches+the+redirect+URI+registered+for+this+client+application.

**Comment by rnehra01** [comment]
Got the same error.

**Comment by sudwebd** [comment]
sorry ,had a bug ,corrected now

**Comment by jasonjoh** [comment]
@sudwebd Glad you figured it out! Could you share what the problem was and how you fixed it in case @rnehra01 is having the same issue?

**Comment by rnehra01** [comment]
The issue is regarding the redirect_uri which was set wrong during app registration.
