### ISSUE TITLE
How to send a mail ? and filter sent items using specific email address ?

### ISSUE THREAD

**Issue by kurianbenny** [jasonjoh/javascript-tutorial#3]
Sir i need to integrate outlook email client to one of my project. i was looking for a solution and i found this tutorial. I have listed the inbox messages based on the filter (by an email address). I need to compose mail and sent via this api and also i need to show sent items for a specific email address. Can you please help me for this ?

**Comment by jasonjoh** [comment]
Graph docs are here: https://developer.microsoft.com/en-us/graph/docs/concepts/overview. How to send message is here: https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/message_send.
