### ISSUE TITLE
Logic of function getUserEmailAddress

### ISSUE THREAD

**Issue by cym1** [jasonjoh/javascript-tutorial#4]
In the function, it checks whether the userEmail already exists in the sessionStorage or not.

However, the userEmail is never stored.

So, maybe we can move "if (sessionStorage.userEmail){ ..." into "getAccessToken(function(accessToken) { ..."
and then add "sessionStorage.userEmail = res.mail" inside "else {callback(res.mail); }"?

**Comment by cym1** [comment]
also, sometimes res.mail is null

**Comment by jasonjoh** [comment]
I believe `res.mail` is null for Outlook.com accounts, in which case it needs to fall back and use `userPrincipalName`. I'll see if I can't push a code fix soon.
